### ISSUE TITLE
Mismatch types for UserInfo struct.

### ISSUE THREAD

**Issue by i7solar** [Fef0/go-5sim#1]
In regards to requesting UserInfo with an API key, this error is given:

**2021/12/12 18:05:33 json: cannot unmarshal number 95.79 into Go struct field UserInfo.rating of type int
exit status**

To correct this error, the UserInfo struct and UserInfo rating function just needs to be swapped from int to float.

**Comment by Fef0** [comment]
Hi! Thank you very much for pointing out this error, I'll review your pull request in a minute and I'll eventually merge it

**Comment by i7solar** [comment]
No worries, have a good one!
